// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sweeft.Console;

#nullable disable

namespace Sweeft.Console.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sweeft.Console.Models.Pupil", b =>
                {
                    b.Property<int>("PupilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PupilID"));

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PupilID");

                    b.ToTable("Pupils");

                    b.HasData(
                        new
                        {
                            PupilID = 1,
                            Class = "SE-123",
                            FirstName = "Giorgi",
                            Gender = "M",
                            LastName = "Giorgadze"
                        },
                        new
                        {
                            PupilID = 2,
                            Class = "SE-123",
                            FirstName = "Aleksandre",
                            Gender = "M",
                            LastName = "Maisuradze"
                        },
                        new
                        {
                            PupilID = 3,
                            Class = "SE-123",
                            FirstName = "Mariam",
                            Gender = "F",
                            LastName = "Davitashvili"
                        });
                });

            modelBuilder.Entity("Sweeft.Console.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FirstName = "Nika",
                            Gender = "M",
                            LastName = "Chkhartishvili",
                            Subject = "History"
                        },
                        new
                        {
                            TeacherId = 2,
                            FirstName = "Zurab",
                            Gender = "M",
                            LastName = "Zurabishvili",
                            Subject = "Biology"
                        });
                });

            modelBuilder.Entity("TeacherPupil", b =>
                {
                    b.Property<int>("PupilID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("PupilID", "TeacherID");

                    b.HasIndex("TeacherID");

                    b.ToTable("TeacherPupil");
                });

            modelBuilder.Entity("TeacherPupil", b =>
                {
                    b.HasOne("Sweeft.Console.Models.Pupil", null)
                        .WithMany()
                        .HasForeignKey("PupilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sweeft.Console.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
